import { AUTO_FIELD, autoPointToField } from '$lib/matchScouting.js';

function escapeXml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function validPoint(point) {
  return Array.isArray(point) && point.length >= 2 && Number.isFinite(Number(point[0])) && Number.isFinite(Number(point[1]));
}

// This deliberately generates a self-contained SVG rather than reaching for a
// browser canvas or native image library. Drive opens SVG files as images, and
// the portable markup keeps an exported route sharp when a coach zooms in.
export function renderAutoPathImage({ eventKey, teamKey, name, alliance = 'red', path = [] }) {
  const ownColor = alliance === 'blue' ? '#2468c7' : '#d12c36';
  const opponentColor = alliance === 'blue' ? '#d12c36' : '#2468c7';
  const points = path.filter(validPoint).map((point) => autoPointToField(point));
  const route = points.map(({ x, y }) => `${x.toFixed(2)},${y.toFixed(2)}`).join(' ');
  const start = points[0];
  const end = points.at(-1);
  const title = `${teamKey || 'Team'} - ${name || 'Autonomous path'}`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="860" viewBox="0 0 1000 537" role="img" aria-labelledby="title description">
  <title id="title">${escapeXml(title)}</title>
  <desc id="description">Saved ${escapeXml(alliance)} alliance autonomous path for ${escapeXml(eventKey || 'the active event')}.</desc>
  <rect width="1000" height="537" fill="#f7f4ed"/>
  <text x="24" y="30" fill="#24221d" font-family="Arial, sans-serif" font-size="18" font-weight="700">${escapeXml(title)}</text>
  <text x="24" y="51" fill="#6b675e" font-family="Arial, sans-serif" font-size="13">${escapeXml(eventKey || 'Event')} | ${escapeXml(alliance)} alliance | Saved autonomous route</text>
  <g transform="translate(0 58)">
    <rect x="8" y="8" width="984" height="471" fill="#666866"/>
    <rect x="8" y="8" width="984" height="471" fill="none" stroke="#202221" stroke-width="7"/>
    <line x1="500" y1="8" x2="500" y2="479" stroke="#d9dad8" stroke-width="2"/>
    <line x1="8" y1="8" x2="8" y2="479" stroke="${ownColor}" stroke-width="8"/>
    <line x1="992" y1="8" x2="992" y2="479" stroke="${opponentColor}" stroke-width="8"/>
    <line x1="258" y1="8" x2="258" y2="479" stroke="${ownColor}" stroke-width="3"/>
    <line x1="742" y1="8" x2="742" y2="479" stroke="${opponentColor}" stroke-width="3"/>
    <g fill="${ownColor}" stroke="#161616" stroke-width="3"><rect x="260" y="76" width="65" height="105"/><rect x="260" y="306" width="65" height="105"/><rect x="260" y="14" width="34" height="55"/><rect x="260" y="418" width="34" height="55"/></g>
    <g fill="${opponentColor}" stroke="#161616" stroke-width="3"><rect x="675" y="76" width="65" height="105"/><rect x="675" y="306" width="65" height="105"/><rect x="706" y="14" width="34" height="55"/><rect x="706" y="418" width="34" height="55"/></g>
    <g fill="#b9bab8" stroke="#171817" stroke-width="5"><rect x="246" y="198" width="92" height="92"/><rect x="662" y="198" width="92" height="92"/></g>
    <g fill="#d8b832" fill-opacity=".55" stroke="#302b14" stroke-width="2" stroke-dasharray="5 5"><rect x="455" y="117" width="90" height="253"/></g>
    ${route ? `<polyline points="${route}" fill="none" stroke="#1d1d1b" stroke-opacity=".65" stroke-width="12" stroke-linejoin="round" stroke-linecap="round"/><polyline points="${route}" fill="none" stroke="#ffd34d" stroke-width="7" stroke-linejoin="round" stroke-linecap="round"/>` : ''}
    ${start ? `<circle cx="${start.x}" cy="${start.y}" r="10" fill="#fff" stroke="#1d1d1b" stroke-width="4"/>` : ''}
    ${end ? `<circle cx="${end.x}" cy="${end.y}" r="9" fill="${ownColor}" stroke="#fff" stroke-width="3"/>` : ''}
  </g>
  <text x="24" y="520" fill="#6b675e" font-family="Arial, sans-serif" font-size="12">Route points: ${points.length} | Generated by Spartans Hub</text>
</svg>`;
}

export function autoPathImageFileName({ eventKey, teamKey, name, createdAt = new Date().toISOString() }) {
  const slug = (value) => String(value || 'untitled')
    .trim()
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'untitled';
  const date = new Date(createdAt);
  const timestamp = (Number.isNaN(date.getTime()) ? new Date() : date).toISOString().replace(/[:.]/g, '-');
  return `${slug(eventKey)}_${slug(teamKey)}_${slug(name)}_${timestamp}.svg`;
}
